const express = require('express');
const sqlite3 = require('sqlite3').verbose(); // Brings in the database engine
const app = express();
const PORT = 3000;
const cors = require('cors');
app.use(cors()); // This opens the gates so Netlify can talk to it!
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(__dirname));

// Ensure this is at the top level of server.js, not nested inside another app.post!
app.post('/api/login', (req, res) => {
    const { email, password } = req.body;

    db.get(`SELECT * FROM users WHERE email = ? AND password = ?`, [email, password], (err, user) => {
        if (err) {
            console.error("Database error:", err);
            return res.status(500).json({ message: "Internal server error" });
        }
        if (!user) {
            return res.status(401).json({ message: "Invalid email or password." });
        }
        res.status(200).json({ message: "Login successful" });
    });
});

// 1. Initialize Database: Creates a local file called 'truegloss.db'
const db = new sqlite3.Database('./truegloss.db', (err) => {
    if (err) console.error("Database connection error:", err.message);
    else console.log("Connected to the True Gloss local database.");
});

// 2. Build the Schema: Creates the 'packages' table if it doesn't exist yet
db.serialize(() => {
    db.run(`CREATE TABLE IF NOT EXISTS packages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        price REAL,
        description TEXT,
        status TEXT,
        category TEXT
    )`);

    db.run(`CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        email TEXT UNIQUE,
        password TEXT,
        role TEXT DEFAULT 'admin'
    )`);
});

// 3. The API Route: Now saves the data permanently into the SQL database
app.post('/api/packages', (req, res) => {
    const { name, price, description, status, category } = req.body;
    
    // The SQL command to insert the new row
    const query = `INSERT INTO packages (name, price, description, status, category) VALUES (?, ?, ?, ?, ?)`;
    
    // Execute the command using the data from your frontend modal
    db.run(query, [name, price, description, status, category], function(err) {
        if (err) {
            console.error("Failed to save package:", err);
            return res.status(500).json({ message: "Error saving to database." });
        }
        
        console.log(`SUCCESS: "${name}" was securely saved to the database!`);
        res.status(200).json({ 
            message: "Package securely saved!", 
            packageId: this.lastID // Sends back the unique ID generated by SQL
        });
    });

    
});


// 4. Fetch All Packages: Pulls data from the database to show on the dashboard
app.get('/api/packages', (req, res) => {
    db.all(`SELECT * FROM packages`, [], (err, rows) => {
        if (err) {
            console.error("Error fetching packages:", err);
            return res.status(500).json({ message: "Error fetching packages" });
        }
        // Sends the rows back to the frontend as a clean JSON array
        res.status(200).json(rows);
    });
});

// 5. Delete a Package: Removes a package from the database based on its ID
app.delete('/api/packages/:id', (req, res) => {
    const packageId = req.params.id;

    // The SQL command to delete a specific row
    db.run(`DELETE FROM packages WHERE id = ?`, packageId, function(err) {
        if (err) {
            console.error("Error deleting package:", err);
            return res.status(500).json({ message: "Failed to delete package." });
        }
        
        console.log(`SUCCESS: Package ID ${packageId} was deleted.`);
        res.status(200).json({ message: "Package deleted successfully!" });
    });
});

// 6. Get a Single Package: Fetches one specific package to pre-fill the edit form
app.get('/api/packages/:id', (req, res) => {
    db.get(`SELECT * FROM packages WHERE id = ?`, [req.params.id], (err, row) => {
        if (err) {
            console.error("Error fetching single package:", err);
            return res.status(500).json({ message: "Error fetching package data." });
        }
        res.status(200).json(row);
    });
});

// 7. Edit a Package: Overwrites the existing database row with new data
app.put('/api/packages/:id', (req, res) => {
    const { name, price, description, status, category } = req.body;
    const packageId = req.params.id;
    const query = `UPDATE packages SET name = ?, price = ?, description = ?, status = ?, category = ? WHERE id = ?`;
    db.run(query, [name, price, description, status, category, packageId], function(err) {
        if (err) {
            console.error("Error updating package:", err);
            return res.status(500).json({ message: "Failed to update package." });
        }
        console.log(`SUCCESS: Package ID ${packageId} was updated.`);
        res.status(200).json({ message: "Package updated successfully!" });
    });
});

// Boot up the server
app.listen(PORT, () => {
    console.log(`True Gloss Admin Server is running on http://localhost:${PORT}`);
});